version: '3.8'

services:
  database:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    networks:
      - dock-db
  migration:
    build: .
    command: "python init_table.py"
    depends_on:
      - database
    networks:
      - dock-db
  app:
    build: .
    command: "python app.py"
    restart: on-failure
    ports:
      - 8081:8080
    depends_on:
      - migration
    networks:
      - dock-db

networks:
  dock-db:
    name: dock-db